### ISSUE TITLE
Duplicate generation of code

### ISSUE THREAD

**Issue by ShayOinif** [Kotlin/kotlinx-rpc#121]
Hello.
One thing I noticed only recently is that you generate in a kmp, shared module, which uses only, let's say - krpc-core, the client for each target.
Is this code really specific to each target?
Couldn't it be generated in common source set and some expect/actual for platform specific in platform specific source set?
I feel like this is a bit redundant and results in a bigger and longer build.
For your notice,
Thanks.

**Comment by Mr3zee** [comment]
Hello! This is how compiler plugins work now, they don't have a common target, and compilation runs for each final target only. So also no Native compilation also, but rather iosX64, iosArm64, etc.

This may change in the future with universal klibs, there was a good talk at kotlin conf about it: https://kotlinconf.com/talks/582224/

**Comment by Mr3zee** [comment]
Yeah, that is mostly true. The only note the reason this happens with with compiler plugins is because a compiler itself compiles code right to a target platform, so a compiler plugin just able to transform some intermediate representation of this code, it doesn't choose where to put the result, the compiler does

**Comment by ShayOinif** [comment]
Hope it will change, or maybe there are some other considerations I am not aware of.
Anyhow, played a bit with ksp and as you said they automatically put code for each target in right source set.
But I don't like it, seems like a workaround of putting it in common main meta data and linking the src dir myself might do the trick for me.
Or am I missing something with the generated/ksp/metadata/commonMain folder?

**Comment by Mr3zee** [comment]
No, I think I does just works like this. But we aware, that the ksp generation will run for each final source set anyway, so you will generate it `n` times and put it into the same directory

**Comment by ShayOinif** [comment]
I don't like using KSP :)
Anyhow, hope that Kotlin will change their packaging process for KMP.

Noticed not long ago that even common code goes into each platform binaries instead of residing in the base common jar of a lib.

When it comes to code generation, it is wasteful to generate same code for each platform on build machine, which makes the build folder to be larger and the build slower, but only bothers the machine that builds the project..

But when creating a lib and all common code is automatically packaged for each lib platform variant, just makes the entire lib heavier and eventually costs more space on maven repo.

Anyhow, this is how KMP works right now, and I saw somewhere plans to change it, hope the will follow soon.
