### ISSUE TITLE
Problem to find targets for apple targets in 0.2.0

### ISSUE THREAD

**Issue by ShayOinif** [Kotlin/kotlinx-rpc#122]
Hello.
I've noticed that in your 0.2.0 release, most desired targets compile ok except apple targets.
On inspection of your .module files in, let's say krpc-core (the multiplatform artifact) I see that there is a wrong relative path to apple artifact, for example:

`
"name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.2.0/core-iossimulatorarm64-0.2.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "core-iossimulatorarm64",
        "version": "0.2.0"
      }
`

the url should be: "url": "../../kotlinx-rpc-core-iossimulatorarm64/0.2.0/kotlinx-rpc-core-iossimulatorarm64-0.2.0.module".

For other targets the url is correct.

This results in error when adding apple targets to kmp module since the desired artifacts are looked in wrong path..

**Comment by Mr3zee** [comment]
Hi! This was fixed here already
https://github.com/Kotlin/kotlinx-rpc/issues/120

**Comment by ShayOinif** [comment]
Oh, OK.
Great.
Simply used already published artifacts for 0.2.0.
Thought it was an official publication.

**Comment by Mr3zee** [comment]
It should've been until I found this problem😅

**Comment by ShayOinif** [comment]
So you will add release soon here in github or should I check once in a while your maven for when you publish new, correct artifacts?

Sorry for all the hassle, I simply really looking forward for this lib to work properly.
Very excited about the concept and on how easily I could write a multiplatform project I'm one place, where interface is clear, type safe, and utilize structured concurrency and flows.

It's the dream for me 🤘

**Comment by Mr3zee** [comment]
Yes, the release will soon appear in the Releases section on the github, and we will make a post in the [Slack channel](https://kotlinlang.slack.com/archives/C072YJ3Q91V)

Thank you for your kind feedback and questions, it is important to us!
