### ISSUE TITLE
Uncahught exception on JS target with kotlinx rpc + ktor transport - 2.1.0 

### ISSUE THREAD

**Issue by ShayOinif** [Kotlin/kotlinx-rpc#125]
Hello.
I gave a thorough run for all targets with new library version 2.1.0!! Congrats on the official release!!

One new issue I found is that on JS target, when creating KtorRPCClient, and server goes away unexpectedly, there
is an uncaught exception that is thrown from the KtorRPCClient (regardless of operations done on the client,
even if I just create it and do nothing with it):

Uncaught runtime errors:
×
ERROR
Already resumed, but proposed with update CompletedExceptionally[WebSocketException: {"target":{},"type":"error","isTrusted":true}]
alreadyResumedError@
resumeImpl@
@

For you attention.
Thank you!

**Comment by Mr3zee** [comment]
Hi! Thank you for the feedback and interest in the lib!
What you describe to me sounds like it should not work on any target, because we didn't cover this case in kRPC yet. 
Anyway, I will take a look in a couple of weeks, thanks, but for now I'm happily afk 😁

**Comment by ShayOinif** [comment]
My bad, this error is very specific to Safari and under weird proxy settings I was under.

In a regular environment with Chrome this doesn't persist.
