### ISSUE TITLE
Connecting to a non-kotlin client/server

### ISSUE THREAD

**Issue by behnawwm** [Kotlin/kotlinx-rpc#145]
How can i share my RPC interface with a non-kotlin client and call it from there?
Is there any way to share the RPC interface? (probably as a .proto file)
How about the opposite way, if my server gives me a .proto file, is there a way to convert it to RPC interface automatically?

**Comment by Mr3zee** [comment]
Hi! It's only Kotlin-to-Kotlin for now.

**Comment by CheeseTastisch** [comment]
> Hi! It's only Kotlin-to-Kotlin for now.

Will there be support for non-Kotlin clients?

**Comment by Mr3zee** [comment]
For now, only gRPC integration is planned, which can be considered a non-Kotlin. Otherwise, nothing is planned so far

**Comment by behnawwm** [comment]
Thanks.
