### ISSUE TITLE
Missing versions in 0.2.2 release

### ISSUE THREAD

**Issue by ShayOinif** [Kotlin/kotlinx-rpc#146]
Hi.
Seems like you published some 0.2.2 artifacts to maven.
Don't know if it was intentional or not.
Anyhow, some artifacts where not published so I had to force 0.2.1 for them in resolution management as follows:

force("org.jetbrains.kotlinx:kotlinx-rpc-krpc-serialization-core:0.2.1")
force("org.jetbrains.kotlinx:kotlinx-rpc-krpc-serialization-json:0.2.1")
force("org.jetbrains.kotlinx:kotlinx-rpc-utils:0.2.1")
force("org.jetbrains.kotlinx:kotlinx-rpc-krpc-server:0.2.1")
force("org.jetbrains.kotlinx:kotlinx-rpc-ksp-plugin:1.9.24-0.2.1")
force("org.jetbrains.kotlinx:kotlinx-rpc-krpc-serialization-core:0.2.1")
force("org.jetbrains.kotlinx:kotlinx-rpc-krpc-serialization-json:0.2.1")

Might be that some other dependencies are missing as well but these are the ones that were missing for my project.

**Comment by Mr3zee** [comment]
Hello! Yes, yesterday, during the publication process Sonatype had an outage, and some artifacts were not published. The repository is currently in a broken state. I've contacted the support, but I suspect that I will not receive any answer until Monday. 

Please, do not use any published versions until they are officially published on the GitHub in the releases section. All publications will also be announced in the Slack channel.
Thank you for your understanding.
