### ISSUE TITLE
Ktor 3.0.0

### ISSUE THREAD

**Issue by CheeseTastisch** [Kotlin/kotlinx-rpc#159]
When will there be support for Ktor 3.0.0, especially on the server, as the client already works with Ktor 3.0.0?

I know Ktor 3.0.0 is currently only in beta, but having support for it asap, maybe even before fully released would be great.

**Comment by Mr3zee** [comment]
Hi! Not discussed yet, but surely the support will be provided. No ETA that I can provide now

**Comment by CheeseTastisch** [comment]
Ok, thanks!

**Comment by CheeseTastisch** [comment]
Does kotlinx-rpc work with wasmJs?
