### ISSUE TITLE
Is it possible to add an Authentication header to the RPC client?

### ISSUE THREAD

**Issue by realityexpander** [Kotlin/kotlinx-rpc#160]
Is it possible to add an Authentication header to the RPC client? 

Like this:

// App.kt
```
suspend fun setupRPC(): NewsService = client.rpc {
	url {
		host = DEV_SERVER_HOST
		port = 8080
		encodedPath = "/api"
	}

	headers {
		append(HttpHeaders.Authorization, "Basic YWRtaW46YWRtaW4=")
	}

	rpcConfig {
		serialization {
			json { }
		}
	}
}.withService()
```

I tried this, and the header is not being added to the requests.

![image](https://github.com/user-attachments/assets/59788b7a-046c-45d3-8fd1-3a82e47337e5)

If this is not the correct functionality, is the work-around to send the authentication along with the RPC calls as a parameter?

**Comment by Mr3zee** [comment]
Hi! Thank you for the report. Looks like a bug to me, I'll take a look

**Comment by EricDeng1001** [comment]
Encountered same problem.

**Comment by realityexpander** [comment]
I'm a RPC newbie... but is it considered safe to pass an Auth string as a parameter, as a temporary workaround? Or would this be a security vulnerability?

**Comment by EricDeng1001** [comment]
I think it's doable but need huge refactoring of code

**Comment by realityexpander** [comment]
> I think it's doable but need huge refactoring of code

What exactly? Passing a authetntication string as a parameter? My ask is if sending this kind of payload would result in a security vulnerability? Or is sending an data in RPC considered secure as its traveling over https?

**Comment by EricDeng1001** [comment]
It's same secure as how https is secure.  I mean when you need to pass a parameter whenever your function need authentication, this cause huge amount of code modification.
I would usually use "aspect" for this kind of task. In client-server case, it is header authentication.

**Comment by realityexpander** [comment]
OK, thank you for confirming it’s secure via HTTPS. The parameter passing is acceptable for now, since header authentication is not available yet...

**Comment by Mr3zee** [comment]
@realityexpander I looked into the code and found that `headers` function you use is the wrong one in Ktor. (`public fun headers(builder: HeadersBuilder.() -> Unit): Headers = Headers.build(builder)`). It does not add headers, but creates and returns a `Headers` instance. The correct way would be the write `headers.append(HttpHeaders.Authorization, "Basic YWRtaW46YWRtaW4=")`

**Comment by realityexpander** [comment]
Ah, I see. 

Confirming: is this the standard pattern for setting up headers?

**Comment by Mr3zee** [comment]
Probably yes, though it's better to ask in the ktor slack, for example, or refer to their docs

**Comment by realityexpander** [comment]
> Probably yes, though it's better to ask in the ktor slack, for example, or refer to their docs

OK thank you!
