### ISSUE TITLE
Kotlin 2.0.20

### ISSUE THREAD

**Issue by mani1232** [Kotlin/kotlinx-rpc#193]
Add support Kotlin 2.0.20

**Comment by Mr3zee** [comment]
Hi! Yes, we know about the demand and we are sorry for the delay. 
The problem is - 2.0.20 broke some compiler plugin API that is really hard to fix rn, so we are making preparations to migrate to the new API

**Comment by chris-hatton** [comment]
Any status on this?  I'm joyfully making `kotlinx.rpc` central to a new Multiplatform project I'm working on; and currently caught in a bind between Xcode 16.0 support not working before 2.0.21 and `kotlinx.rpc` not working after it!

Thanks for RPC, it's the most exciting Kotlin ecosystem library to hit the decks for a good while - very excited about what it can enable us to builld.

**Comment by Mr3zee** [comment]
Hi @chris-hatton ! Thank you for the kind feedback!

I'm currently working on the blockers that prevent 2.0.20+ update and the next minor release will support all latest missing Kotlin versions. No ETA though

**Comment by Rattlyy** [comment]
@Mr3zee does this library not have a stable release cycle yet?
