### ISSUE TITLE
krpc-ktor-server to support Multiplatform

### ISSUE THREAD

**Issue by tristancaron** [Kotlin/kotlinx-rpc#209]
Looking at the content of this module, it does seem that it could be moved under `commonMain`. Its dependencies are supporting multiplatform.

https://github.com/Kotlin/kotlinx-rpc/blob/main/krpc/krpc-ktor/krpc-ktor-server/build.gradle.kts

**Comment by Mr3zee** [comment]
Hi! The server module uses JVM reflection to invoke service methods, so the update is not straightforward. But we plan to do it eventually, yes

**Comment by TristanCaronUnity** [comment]
Ah missed that one. Thanks for the update.

**Comment by Zymus** [comment]
> Hi! The server module uses JVM reflection to invoke service methods, so the update is not straightforward. But we plan to do it eventually, yes

Thanks for the JVM tip. I was struggling getting a MP with mingw setup, and hadn't targeted jvm in my project yet. Adding jvm and removing mingw allowed me to build.

**Comment by xeodon** [comment]
If you look at the source code, there is still weak support for code generation in the project.  Therefore, hacks at the JVM level.

**Comment by Mr3zee** [comment]
It's actually a duplicate for #83
