### ISSUE TITLE
Kotlin `2.1.0` support (as documentation suggests?)

### ISSUE THREAD

**Issue by Jire** [Kotlin/kotlinx-rpc#247]
There is no Kotlin `2.1.0` support seemingly, even though the documentation suggests that.

This is due to missing updated `2.1.0-0.4.0` versions of `kotlinx-rpc-compiler-plugin-cli` and other libraries.

**Comment by Mr3zee** [comment]
Yep, sorry, I accidentally updated the docs before the release
