### ISSUE TITLE
Duplicate Imports Issue in Code Generation

### ISSUE THREAD

**Issue by anton-knyazev** [Kotlin/kotlinx-rpc#94]
While experimenting with the ktor-all-platforms-app example, I observed an anomaly during the code generation phase. Specifically, when extending the UserServiceClient class by adding a new function (hello2) that mirrors the functionality of an existing function (hello), the code generation process unexpectedly produces duplicate import statements for UserData. This occurs despite the logical expectation that both functions should share the same import statement for UserData, resulting in unnecessary redundancy and potential confusion.

**Comment by Mr3zee** [comment]
Hi! Thanks for noticing
As we are currently moving from KSP to compiler plugins, this issue will be fixed by itself when were are done.

**Comment by Mr3zee** [comment]
Fixed in #162
