### ISSUE TITLE
Add support for Wasm

### ISSUE THREAD

**Issue by SalomonBrys** [Kotlin/kotlinx-rpc#95]
Please deploy artifact for the `wasmJs` & `wasmWasi` targets.

**Comment by ShayOinif** [comment]
I would love that too if it is possible.
RIght now on compose multiplatform I use Canvas on JS target to make my UI just because of no wasJs target :/

**Comment by sgammon** [comment]
Even if it is _just_ annotations, so we can annotate classes in `commonMain` with wasm targets

**Comment by Mr3zee** [comment]
@sgammon can you please elaborate on your comment? What annotations are you talking about?

**Comment by sgammon** [comment]
@Mr3zee Sorry, I mean annotations or interfaces. Things that can safely be included in a common target, so that we can at least create our RPC interfaces in a common target, even if we can't implement them there yet.

**Comment by Mr3zee** [comment]
I see, thank you
I'll if this is worth to do now, or it would be easier just to support WASM fully

**Comment by sylvain-barrepersyn** [comment]
If I understand correctly, this feature will be delivered in the next version of kotlinx-rpc. Do you have any idea when ?

**Comment by Mr3zee** [comment]
No ETA for now

**Comment by sgammon** [comment]
@Mr3zee Could a WASM target be added which is functionally empty? Or even just has `kotlinx.rpc.RPC` defined as an interface? That would be sufficient for our needs for now.

Because KotlinX RPC does not ship a WASM target, we cannot use KotlinX RPC in any source set which ships for WASM, or which _ultimately is depended on downstream_ by a source set for WASM, whether or not those source sets make use of RPC.

**Comment by sgammon** [comment]
I would humbly ask that you reconsider because KotlinX RPC is the only KotlinX library we cannot use due to this reason

**Comment by sylvain-barrepersyn** [comment]
I very agree, just to compile projet and permit to have a shared module (multiplatform one) in projects which have the goal to target WASM in the future. It can be useful to juste have an empty dependency compliant to this target.

**Comment by Mr3zee** [comment]
WASI is blocked by https://github.com/oshai/kotlin-logging/issues/433, `wasmJs` is WIP

**Comment by sgammon** [comment]
I would actually be surprised to find `oshai/kotlin-logging` as a dependency to RPC...

**Comment by sgammon** [comment]
@Mr3zee Am I correct in my assumption that this is the only place a KotlinX library depends on something outside of `kotlin-stdlib` and other KotlinX libraries?

**Comment by Mr3zee** [comment]
@sgammon technically, yes (though I'm not sure about all of the other kotlinx libs). 

But there is a little more to that. Our core module depends only on atomicfu, coroutines and serialization. Core module and codegen plugins make the foundation of the library, so being dependent on core libs is only logical.

Then kRPC (and other modules in work) is an implementation of the library foundation, more complex than core itself, and requires external dependencies. And while logging is a debatable topic here, and it may happen, that kRPC will also be dependent only on core libs, for gRPC, for example, it surely will not be the case, as we will use existing platform specific libs to provide this integration. Implementing gRPC protocol from scratch is not what we want to do.

**Comment by sgammon** [comment]
@Mr3zee Thank you so much for shipping this one!

**Comment by lukewarlow** [comment]
Looks like wasi is supported in kotlin-logging by https://github.com/oshai/kotlin-logging/pull/551
